<a href="https://colab.research.google.com/github/AanishRahmani/back_prop_regression_and_classification/blob/main/back_prop_regression_impl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [4]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','iq','lpa'])

iq=iq*10

In [5]:
df

cgpa  iq  lpa
0     8   8    4
1     7   9    5
2     6  10    6
3     5  12    7

# initializing parameters

take architecture of model

(how many total layers are their i am going with 2 i/p 2 hidden and 1 o/p layer)

hence 9 params will be created my initial weight is 0.1 and bias is 0

In [6]:
def init_params(layers_dim):
  np.random.seed(3)
  params={}
  l=len(layers_dim)
  for i in range(1,l):
    params['W'+str(i)]=np.ones((layers_dim[i-1],layers_dim[i]))*0.1
    params['b'+str(i)]=np.zeros((layers_dim[i],1))
  return params


In [7]:
init_params([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [8]:
def linear_forward(A_prev,W,b):
  Z=np.dot(W.T,A_prev)+b
  return Z

In [16]:
# main forward prop

def forward_prop(X,params):
  A=X
  L=len(params)//2
  for l in range(1,L+1):
    A_prev=A
    Wl=params['W'+str(l)]
    bl=params['b'+str(l)]
    print("A"+str(l-1)+': ',A_prev)
    print("W"+str(l)+': ',Wl)
    print("b"+str(l)+': ',bl)
    print('---'*20)
    A=linear_forward(A_prev,Wl,bl)
    print("A"+str(l)+': ',A)
    print('**'*20)
  return A,A_prev

In [17]:
X=df[['cgpa','iq']].values[0].reshape(2,1)
y=df[['lpa']].values[0][0]

In [18]:
X

array([[8],
       [8]])

In [19]:
y

np.int64(4)

In [20]:
parameters=init_params([2,2,1])

In [21]:
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [25]:
y_hat,A1=forward_prop(X,parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
------------------------------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
------------------------------------------------------------
A2:  [[0.32]]
****************************************


In [28]:
# loss for first student
# (y-.32)**2

y_hat=y_hat[0][0]

In [30]:
A1

array([[1.6],
       [1.6]])

In [35]:
def update_parameters(parameters,y,y_hat,A1,X):
  y = y.item() if isinstance(y, np.ndarray) else y
  y_hat = y_hat.item() if isinstance(y_hat, np.ndarray) else y_hat

  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [49]:
update_parameters(parameters,y,y_hat,A1,X)

In [50]:
parameters

{'W1': array([[0.17228732, 0.23472498],
        [0.17302137, 0.23644246]]),
 'b1': array([[0.01244844],
        [0.01259298]]),
 'W2': array([[0.24222104],
        [0.24759357]]),
 'b2': array([[0.25976603]])}

In [51]:
X=df[['cgpa','iq']].values[1].reshape(2,1)
y=df[['lpa']].values[1][0]
y_hat,A1=forward_prop(X,parameters)

A0:  [[7]
 [9]]
W1:  [[0.17228732 0.23472498]
 [0.17302137 0.23644246]]
b1:  [[0.01244844]
 [0.01259298]]
------------------------------------------------------------
A1:  [[2.77565201]
 [3.78364997]]
****************************************
A1:  [[2.77565201]
 [3.78364997]]
W2:  [[0.24222104]
 [0.24759357]]
b2:  [[0.25976603]]
------------------------------------------------------------
A2:  [[1.86889476]]
****************************************


In [52]:
update_parameters(parameters,y,y_hat,A1,X)

In [53]:
parameters

{'W1': array([[0.18366713, 0.24935616],
        [0.18491339, 0.2517322 ]]),
 'b1': array([[0.01407413],
        [0.01429184]]),
 'W2': array([[0.25960276],
        [0.27128758]]),
 'b2': array([[0.27754979]])}

In [54]:
X=df[['cgpa','iq']].values[2].reshape(2,1)
y=df[['lpa']].values[2][0]
y_hat,A1=forward_prop(X,parameters)

A0:  [[ 6]
 [10]]
W1:  [[0.18366713 0.24935616]
 [0.18491339 0.2517322 ]]
b1:  [[0.01407413]
 [0.01429184]]
------------------------------------------------------------
A1:  [[2.9652108 ]
 [4.02775081]]
****************************************
A1:  [[2.9652108 ]
 [4.02775081]]
W2:  [[0.25960276]
 [0.27128758]]
b2:  [[0.27754979]]
------------------------------------------------------------
A2:  [[2.14000549]]
****************************************


In [55]:
update_parameters(parameters,y,y_hat,A1,X)

In [56]:
parameters

{'W1': array([[0.19675224, 0.27116468],
        [0.19891969, 0.27507604]]),
 'b1': array([[0.01625498],
        [0.01662623]]),
 'W2': array([[0.28249416],
        [0.30238178]]),
 'b2': array([[0.31010176]])}

In [57]:
X=df[['cgpa','iq']].values[3].reshape(2,1)
y=df[['lpa']].values[3][0]
y_hat,A1=forward_prop(X,parameters)

A0:  [[ 5]
 [12]]
W1:  [[0.19675224 0.27116468]
 [0.19891969 0.27507604]]
b1:  [[0.01625498]
 [0.01662623]]
------------------------------------------------------------
A1:  [[3.3870525]
 [4.6733621]]
****************************************
A1:  [[3.3870525]
 [4.6733621]]
W2:  [[0.28249416]
 [0.30238178]]
b2:  [[0.31010176]]
------------------------------------------------------------
A2:  [[2.68006383]]
****************************************


In [58]:
update_parameters(parameters,y,y_hat,A1,X)

In [59]:
parameters

{'W1': array([[0.21021998, 0.30348726],
        [0.21372666, 0.31061277]]),
 'b1': array([[0.01894853],
        [0.01958762]]),
 'W2': array([[0.31175786],
        [0.34275903]]),
 'b2': array([[0.3513989]])}

In [66]:
# epoch impl
parameters = init_params([2,2,1])
epochs = 10

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'iq']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]



    y_hat,A1 = forward_prop(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters


A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
------------------------------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
------------------------------------------------------------
A2:  [[0.32]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
------------------------------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
****************************************
A1:  [[1.70612461]
 [1.70612461]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
------------------------------------------------------------
A2:  [[0.50054357]]
****************************************
A0:  [[ 6]
 [10]]
W1:  [[0.11458955 0.1168776 ]
 [0.11458955 0.1168776 ]]
b1:  [[0.0019667]
 [0.0019667]]
------------------------------------------------------------
A1:  [[1.83539945]
 [1.87200826]]
*

{'W1': array([[0.251385  , 0.42030991],
        [0.26250745, 0.45149331]]),
 'b1': array([[0.02847052],
        [0.03098528]]),
 'W2': array([[0.42075476],
        [0.49891207]]),
 'b2': array([[0.50135566]])}

In [67]:

def forward_prop__(X,params):
  A=X
  L=len(params)//2
  for l in range(1,L+1):
    A_prev=A
    Wl=params['W'+str(l)]
    bl=params['b'+str(l)]
    # print("A"+str(l-1)+': ',A_prev)
    # print("W"+str(l)+': ',Wl)
    # print("b"+str(l)+': ',bl)
    # print('---'*20)
    A=linear_forward(A_prev,Wl,bl)
    # print("A"+str(l)+': ',A)
    # print('**'*20)
  return A,A_prev

In [68]:
# epoch impl
parameters = init_params([2,2,1])
epochs = 10

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'iq']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]



    y_hat,A1 = forward_prop__(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters


Epoch -  1 Loss -  25.321744156025517
Epoch -  2 Loss -  18.320004165722047
Epoch -  3 Loss -  9.473661050729628
Epoch -  4 Loss -  3.2520938634031613
Epoch -  5 Loss -  1.3407132589299962
Epoch -  6 Loss -  1.1726178458115697
Epoch -  7 Loss -  1.2331289135532644
Epoch -  8 Loss -  1.2686856723180788
Epoch -  9 Loss -  1.282007891421992
Epoch -  10 Loss -  1.2866806711744867


{'W1': array([[0.251385  , 0.42030991],
        [0.26250745, 0.45149331]]),
 'b1': array([[0.02847052],
        [0.03098528]]),
 'W2': array([[0.42075476],
        [0.49891207]]),
 'b2': array([[0.50135566]])}

#using keras


In [69]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [70]:
model =Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [71]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [72]:
model.get_weights()

[array([[ 1.1552657 , -0.13255131],
        [-0.55344325,  0.31228757]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.1498954 ],
        [-0.49335682]], dtype=float32),
 array([0.], dtype=float32)]

In [73]:
# making the weights similar to mine

new_weights=[np.array([[0.1,0.1],[0.1,0.1]]),
             np.array([0.,0.]),
             np.array([[0.1],[0.1]]),
             np.array([0.])]

In [74]:
model.set_weights(new_weights)


In [76]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [77]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [85]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=10,verbose=1,batch_size=1)

Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7218
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.6313
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.4052 
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8572 
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6212 
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6926 
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4648 
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.7074 
Epoch 9/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4200 
Epoch 10/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6293 
