<a href="https://colab.research.google.com/github/AanishRahmani/back_prop_regression_and_classification/blob/main/back_prop_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd


In [3]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'iq', 'placed'])

In [4]:
df.head()

cgpa  iq  placed
0     8   8       1
1     7   9       1
2     6  10       0
3     5   5       0

In [5]:
def initialize_parameters(layer_dims):

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))


  return parameters

In [15]:
def sigmoid(Z):
  A=1/(1+np.exp(Z))
  return A

In [16]:
def liner_forward(A_prev, W, b):
  Z = np.dot(W.T, A_prev) + b
  A = sigmoid(Z)
  return A

In [28]:
# L-layer feed forward

def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2
  for l in range(1, L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    # print("A"+str(l-1)+": ", A_prev)
    # print("W"+str(l)+": ", Wl)
    # print("b"+str(l)+": ", bl)
    # print("--"*20)

    A = liner_forward(A_prev, Wl, bl)
    # print("A"+str(l)+": ", A)
    # print("**"*20)

  return A,A_prev


In [21]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [22]:
X = df[['cgpa', 'iq']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['placed']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[0.16798161]
 [0.16798161]]
****************************************
A1:  [[0.16798161]
 [0.16798161]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.49160171]]
****************************************
Loss for this student -  0.7100864245263375


{'W1': array([[0.10000568, 0.10000568],
        [0.10000568, 0.10000568]]),
 'b1': array([[7.10617412e-07],
        [7.10617412e-07]]),
 'W2': array([[0.10000854],
        [0.10000854]]),
 'b2': array([[0.10005938]])}

In [24]:
X = df[['cgpa', 'iq']].values[2].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['placed']].values[2][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

A0:  [[ 6]
 [10]]
W1:  [[0.10000568 0.10000568]
 [0.10000568 0.10000568]]
b1:  [[7.10617412e-07]
 [7.10617412e-07]]
----------------------------------------
A1:  [[0.1679688]
 [0.1679688]]
****************************************
A1:  [[0.1679688]
 [0.1679688]]
W2:  [[0.10000854]
 [0.10000854]]
b2:  [[0.10005938]]
----------------------------------------
A2:  [[0.46663565]]
****************************************
Loss for this student -  0.6285505067770137


{'W1': array([[0.10000177, 0.09999916],
        [0.10000177, 0.09999916]]),
 'b1': array([[5.84648522e-08],
        [5.84648522e-08]]),
 'W2': array([[0.1000007],
        [0.1000007]]),
 'b2': array([[0.09995404]])}

In [25]:
X = df[['cgpa', 'iq']].values[3].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['placed']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

A0:  [[5]
 [5]]
W1:  [[0.10000177 0.09999916]
 [0.10000177 0.09999916]]
b1:  [[5.84648522e-08]
 [5.84648522e-08]]
----------------------------------------
A1:  [[0.26893793]
 [0.26894305]]
****************************************
A1:  [[0.26893793]
 [0.26894305]]
W2:  [[0.1000007]
 [0.1000007]]
b2:  [[0.09995404]]
----------------------------------------
A2:  [[0.4616399]]
****************************************
Loss for this student -  0.6192276132017247


{'W1': array([[0.09999723, 0.09999463],
        [0.09999723, 0.09999463]]),
 'b1': array([[-8.49060512e-07],
        [-8.49071450e-07]]),
 'W2': array([[0.09998829],
        [0.09998829]]),
 'b2': array([[0.09994212]])}

In [29]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 50

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'iq']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['placed']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append(-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  0.6800150752158843
Epoch -  2 Loss -  0.693031158329821
Epoch -  3 Loss -  0.6930310576624739
Epoch -  4 Loss -  0.6930309570056084
Epoch -  5 Loss -  0.6930308563592238
Epoch -  6 Loss -  0.693030755723319
Epoch -  7 Loss -  0.6930306550978931
Epoch -  8 Loss -  0.6930305544829454
Epoch -  9 Loss -  0.6930304538784746
Epoch -  10 Loss -  0.6930303532844803
Epoch -  11 Loss -  0.693030252700961
Epoch -  12 Loss -  0.6930301521279161
Epoch -  13 Loss -  0.6930300515653447
Epoch -  14 Loss -  0.6930299510132456
Epoch -  15 Loss -  0.693029850471618
Epoch -  16 Loss -  0.6930297499404614
Epoch -  17 Loss -  0.6930296494197743
Epoch -  18 Loss -  0.6930295489095561
Epoch -  19 Loss -  0.6930294484098054
Epoch -  20 Loss -  0.693029347920522
Epoch -  21 Loss -  0.6930292474417045
Epoch -  22 Loss -  0.693029146973352
Epoch -  23 Loss -  0.6930290465154638
Epoch -  24 Loss -  0.6930289460680391
Epoch -  25 Loss -  0.6930288456310764
Epoch -  26 Loss -  0.6930287452045751
E

{'W1': array([[0.10013599, 0.10008017],
        [0.10013607, 0.10008023]]),
 'b1': array([[-3.49320725e-06],
        [-3.48648212e-06]]),
 'W2': array([[0.09988263],
        [0.09988269]]),
 'b2': array([[0.09983652]])}

In [30]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [31]:
model=Sequential()

model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [32]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [33]:
model.get_weights()

[array([[-0.3007754 ,  0.2803663 ],
        [ 1.2213227 ,  0.77504003]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.6387547],
        [1.164126 ]], dtype=float32),
 array([0.], dtype=float32)]

In [34]:

new_weights=[np.array([[0.1,0.1],[0.1,0.1]]),
             np.array([0.,0.]),
             np.array([[0.1],[0.1]]),
             np.array([0.])]

In [35]:
model.set_weights(new_weights)

In [36]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [37]:
optimizers=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizers)

In [38]:
model.fit(df.iloc[:,0:-1].values,df['placed'].values,epochs=50,verbose=1,batch_size=1)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.7173
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6739 
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7132 
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7313 
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6723 
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7060 
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7059 
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7020 
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7020 
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7281 
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7121 
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6831 
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7274 
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6730 
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6842
Epoch 16/50
4/4 ━━━━━━━━━━━━━━━━━━